- name: Create the directories
  become: yes
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: root
    group: "101"
    mode: "0770"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt"
      - "{{ docker_dir }}/{{ container_name }}/nginx"
      - "{{ docker_dir }}/{{ container_name }}/www"

- name: Make sure that {{ container_name }} container is running
  docker_container:
    name: "{{ container_name }}"
    image: bunkerity/bunkerized-nginx
    pull: yes
    cap_drop:
      - ALL
    # disable setuid/setgid
    security_opts:
      - no-new-privileges
    tmpfs:
      - /tmp
    restart_policy: always
    ports:
      - 80:8080
      - 443:8443
    # bunkerized-nginx runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/nginx:/etc/nginx"
      - "{{ docker_dir }}/{{ container_name }}/www:/www:ro"
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt:/etc/letsencrypt"
    env:
      "SERVER_NAME": "{{ blog_host }}"
      "AUTO_LETS_ENCRYPT": "yes"
      "REDIRECT_HTTP_TO_HTTPS": "yes"
      "USE_REMOTE_API": "no"
      "DISABLE_DEFAULT_SERVER": "yes"
      "USE_CLIENT_CACHE": "yes"
      "USE_GZIP": "yes"