---
#
# Tasks and roles for all hosts
#
- hosts: fleet
  gather_facts: no

  pre_tasks:
    - import_tasks: tasks/ssh_juggle_port.yml
      tags:
        - port

- hosts: fleet
  become: yes

  roles:
    #
    # Basics
    #
    - role: system
      tags:
        - system

    - role: neovim
      tags:
        - neovim

    - role: geerlingguy.security
      tags:
        - security

    - role: docker
      tags:
        - docker

    - role: network/avahi
      tags:
        - avahi

    - role: chriswayg.msmtp-mailer
      tags:
        - msmtp

    - role: oefenweb.dns
      tags:
        - dns

    - role: geerlingguy.ntp
      tags:
        - ntp


    #
    # Security
    #
    - role: security/fail2ban
      tags:
      - fail2ban
      when: enable_fail2ban | default(False)

    - role: security/iptables
      tags:
      - iptables
      when: enable_iptables | default(False)

    - role: security/crowdsec
      tags:
      - crowdsec
      when: enable_crowdsec | default(False)

    - role: security/endlessh
      tags:
      - endlessh
      when: enable_endlessh | default(False)

    #
    # Network
    #
    - role: network/swag
      become: no
      tags:
        - swag
        - containers
      when: enable_swag_public | default(False) or enable_swag_internal | default(False)

    - role: network/bunkerized-nginx
      become: no
      tags:
        - bunkerized-nginx
        - containers
      when: enable_bunkerized_nginx | default(False)

    - role: network/wireguard
      become: no
      tags:
        - wireguard
        - containers
      when: enable_wireguard | default(False)

    - role: network/ikev2
      become: no
      tags:
        - ikev2
        - containers
      when: enable_ikev2 | default(False)

    - role: network/ddclient
      become: yes
      when: enable_ddclient | default(False)
      tags:
        - ddclient

    - role: network/duckdns
      become: no
      when: enable_duckdns | default(False)
      tags:
        - duckdns

    - role: network/cloudflare-ddns
      become: no
      tags:
        - cloudflare-ddns
        - containers
      when: enable_cloudflare_ddns | default(False)

    - role: network/pihole
      become: no
      when: enable_pihole | default(False)
      tags:
        - pihole
        - containers

    - role: network/ikev2
      become: no
      when: enable_ikev2 | default(False)
      tags:
        - containers
        - ikev2


    #
    # Filesystems
    #
    - role: filesystems/mergerfs
      become: yes
      tags:
        - mergerfs
      when: enable_nas_stuff | default(False)

    - role: filesystems/mounts
      become: yes
      tags:
        - mounts
      when: enable_nas_stuff | default(False)

    - role: filesystems/hd-idle
      become: yes
      tags:
        - hd-idle
      when: enable_nas_stuff | default(False)

    - role: stuvusit.smartd
      become: yes
      tags:
        - smartd
      when: enable_nas_stuff | default(False)

    - role: ironicbadger.ansible_role_snapraid
      become: yes
      tags:
        - snapraid
      when: enable_nas_stuff | default(False)

    #
    # Homer
    #
    - role: homer
      become: no
      tags:
        - homer
        - containers
      when: enable_homer | default(False)


    #
    # Flame
    #
    - role: containers/system/flame
      become: no
      tags:
        - flame
        - containers
      when: enable_flame | default(False)



    #
    # System
    #
    - role: containers/system/jackett
      become: no
      tags:
        - jackett
        - containers
      when: enable_jackett | default(False)

    - role: containers/system/authelia
      become: no
      tags:
        - authelia
        - containers
      when: enable_authelia | default(False)

    - role: containers/system/watchtower
      become: no
      tags:
        - watchtower
        - containers

    - role: containers/system/unifi
      become: no
      tags:
        - unifi
        - containers
      when: enable_unifi | default(False)

    #
    # Media
    #
    - role: containers/media/deluge
      become: no
      tags:
        - deluge
        - containers
      when: enable_deluge | default(False)

    - role: containers/media/sonarr
      become: no
      tags:
        - sonarr
        - containers
      when: enable_sonarr | default(False)

    - role: containers/media/radarr
      become: no
      tags:
        - radarr
        - containers
      when: enable_radarr | default(False)

    - role: containers/media/booksonic
      become: no
      tags:
        - booksonic
        - containers
      when: enable_booksonic | default(False)

    - role: containers/media/plex
      become: no
      tags:
        - plex
        - containers
      when: enable_plex | default(False)

    - role: containers/media/jellyfin
      become: no
      tags:
        - jellyfin
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/media/openbooks
      become: no
      tags:
        - openbooks
        - containers
      when: enable_openbooks | default(False)

    #
    # Services
    #
    - role: containers/services/photoprism
      become: no
      tags:
        - photoprism
        - containers
      when: enable_photoprism | default(False)

    - role: containers/services/nextcloud
      become: no
      tags:
        - nextcloud
        - containers
      when: enable_nextcloud | default(False)

    - role: containers/services/vaultwarden
      become: no
      tags:
        - vaultwarden
        - containers
      when: enable_vaultwarden | default(False)

    #
    # Home automation
    #
    - role: containers/homeautomation/deconz
      tags:
        - deconz
        - smarthome
        - containers
      when: enable_deconz | default(False)

    - role: containers/homeautomation/homeassistant
      become: no
      tags:
        - homeassistant
        - smarthome
        - containers
      when: enable_homeassistant | default(False)



    - role: containers/homeautomation/mqtt
      become: no
      tags:
        - mqtt
        - smarthome
        - containers
      when: enable_homeassistant | default(False)

    #
    # Samba
    #
    - role: bertvv.samba
      become: yes
      tags:
        - samba
      when: enable_nas_stuff | default(False)
