- name: Install necessary packages
  apt:
    pkg:
      - git
      - snapd
      - vim
    state: present
- name: Install emacs from snap
  snap:
    state: present
    classic: yes
    name: emacs
- name: Pull in doom emacs
  command: "git clone --depth 1 https://github.com/hlissner/doom-emacs /home/{{user.stdout}}/.emacs.d"
- name: Install doom-emacs
  command: "/home/{{user.stdout}}/.emacs.d/bin/doom install"
