- name: Install necessary packages
  apt:
    pkg:
      - git
      - snapd
      - vim
    state: present
- name: Install emacs from snap
  snap:
    state: present
    classic: yes
    name: kubectl
