- name: Install default packages
  become: yes
  apt:
    pkg:
      - snapd
      - vim
    state: present
- name: Install multipass from snap
  snap:
    state: present
    classic: yes
    channel: "beta"
    name: multipass
- name: Install microk8s from snap
  snap:
    state: present
    classic: yes
    name: microk8s
