#!/bin/bash

install_files=$Dotfiles/installers

setup_one(){
    if is_ubuntu; then
        location="$install_files/ubuntu/$1"
        name=$(basename "$location")
        echo "Executing script: ${name} from $location"
        . $location
    fi
    if is_archlinux; then
        location="$install_files/archlinux/$1"
        name=$(basename "$location")
        echo "Executing script: ${name} from $location"
        . $location
    fi
    if is_mac; then
        echo "Not yet supported or setup"
    fi
}

setup_every_one(){
    location="$install_files/every/$1"
    name=$(basename "$location")
    echo "Executing script: ${name} from $location"
    . $location
}

setup_every(){
    location="$install_files/every/$1"
    for f in "$location"/*.sh; do
        name=$(basename "$f")
        echo "Executing script: ${name}"
        . $f
    done
}

setup(){
    if is_ubuntu; then
        location="$install_files/ubuntu/$1"
        for f in "$location"/*.sh; do
          name=$(basename "$f")
          echo "Executing script: ${name}"
          . $f
        done
    fi
    if is_archlinux; then
        location="$install_files/archlinux/$1"
        for f in "$location"/*.sh; do
          name=$(basename "$f")
          echo "Executing script: ${name}"
          . $f
        done
    fi
    if is_mac; then
        echo "Not yet supported or setup"
    fi
}
