#!/bin/bash

is_bash=`echo $0 | grep -i "bash"`
is_zsh=$(echo $0 | grep -i "zsh")


if [ -n is_bash ]; then
    eval "$(mise activate bash)"
fi


if [ -n is_zsh ]; then
    eval "$(mise activate zsh)"
fi
