#!/bin/bash

alias gvim="/usr/bin/vim"
alias ovim="/usr/bin/vim"
alias vim="nvim"

if [[ ! -h "$HOME/.config/nvim" ]]; then
  ln -s "$Dotfiles/nvim" "$HOME/.config/nvim"
fi

tvim() {
  current_dir=$(pwd) || "./"
  nvim_session_file="${current_dir}/.nvim/default"
  echo "Current dir: ${current_dir} | Possible session file: ${nvim_session_file}"
  if [[ -f "$nvim_session_file" ]]; then
    nvim -S "$nvim_session_file"
  else
    nvim
  fi
}
