#!/bin/env bash

alias vim="tvim"

tvim() {
  current_dir=$(pwd) || "./"
  echo "Current dir: ${current_dir}"
  nvim_session_file="${current_dir}/.nvim/default"
  echo "Possible session file: ${nvim_session_file}"
  if [[ -f "$nvim_session_file" ]]; then
    nvim -S "$nvim_session_file"
  else
    nvim
  fi
}

# vim() {
#   tvim
# }
