#!/bin/bash

if  no_command 'argon2-cli'; then
  if no_command npm; then
     npm install -g argon2-cli
  fi
fi

hash_argon2() {
  echo -n "$1"| argon2-cli -e
}


export NVM_DIR="$HOME/.nvm"
export USE_NVM=1
NVM_PREFIX=$(brew --prefix nvm)
[ -s "$NVM_PREFIX/nvm.sh" ] && \. "$NVM_PREFIX/nvm.sh" # This loads nvm
[ -s "$NVM_PREFIX/etc/bash_completion.d/nvm" ] && \. "$NVM_PREFIX/etc/bash_completion.d/nvm"  # This loads nvm bash_completion