#!/bin/env bash

export EDITOR='nvim'

export GEM_HOME=$HOME/.gems

export GOBASE=$HOME/go

export GITHUB=$SRC/github.com

export NPM=$HOME/.node_modules
export GETH=$HOME/local/geth
export BREWOPT=/opt/homebrew/opt/
export LINUXBREW=/home/linuxbrew/.linuxbrew

export ANDROIDSDK=$HOME/Library/Android/sdk
export NIX_PROFILE_HOME=$HOME/.nix-profile

export LDFLAGS="-L/usr/local/opt/ncurses/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include"

export NODE_OPTIONS="--max-old-space-size=4096"
export GOPATH="$HOME/go"

export EMCC=$GITHUB/juj/emsdk
export BOOST_ROOT=/usr/boost
export ANACONDA_PATH=$HOME/anaconda3

export BOX_BIN=$HOME/box.bin
export BOX_ROOT=$HOME/Boxd/
export BOX_DOCS=$HOME/Documents/box/

export BOX_FORMULAS=$HOME/Documents/box/box.formulas
export BOX_DEV=$HOME/Documents/box/box.dev
export EWE_PLATFORM=$BOX_DEV/ewe_platform

export USR_LOCAL=$HOME/.local
export LOCAL_VAR=$HOME/.local/var
export LOCAL_SHARE=$HOME/.local/share

export PYENV_ROOT="$HOME/.pyenv"
export SDKMAN_DIR="$HOME/.sdkman"
export RBENV=$HOME/.rbenv/
export ANDROID_HOME=$USR_LOCAL/android
export NODE_MODULES=$HOME/node_modules
export ANDROID_SDK_BIN=$ANDROID_HOME/sdk/cmdline-tools/latest/bin
export ANDROID_TOOLS_BIN=$ANDROID_HOME/sdk/tools/bin


export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
export PATH=$GETH/:$ANDROIDSDK/platform-tools/:$HOME/.local/bin:$HOME/.cargo/bin:$Devlabs/bin:$USR_LOCAL/bin:$PATH
export PATH=$HOME/.rbenv/bin:$GEM_HOME/bin::$GOBASE/bin:$BREWOPT:/usr/local/sbin:$HOME/local/gecko:$PATH
export PATH=$HOME/.local/go/bin:$HOME/.rustup/bin:$HOME/.cargo/bin:/usr/local/go/bin:$HOME/Lab/bin:$PATH
export PATH=$NODE_MODULES/bin:$NODE_MODULES/.bin:$LINUXBREW/bin:$Projects/bin:$HOME/local/bin:$HOME/local/go/bin:$HOME/.cargo/bin:$PATH
export PATH=$ANDROID_TOOLS_BIN:$ANDROID_SDK_BIN:$BOX_BIN:$PATH
export PATH="$PYENV_ROOT/bin:$PATH"

if [ -e $HOME/.profile.custom ]; then . $HOME/.profile.custom; fi # load .profile.custom
if [ -e $HOME/.profile.firebase ]; then . $HOME/.profile.firebase; fi # load .profile.custom
if [ -e $HOME/.profile.git ]; then . $HOME/.profile.git; fi # load .profile.custom
if [ -e $HOME/.profile.linode ]; then . $HOME/.profile.linode; fi # load .profile.custom


