#!/bin/bash

if no_command sops; then
  if has_command brew; then
    brew install sops
  fi
fi

export SOPS_AGE_KEY_FILE=$HOME/.sops/key.txt

sops_encrypt() {
  sops --encrypt --age $(cat $SOPS_AGE_KEY_FILE | grep -oP "public key: \K(.*)") --encrypted-regex '^(data|stringData)$' --in-place "$@"
}
