#!/bin/bash

# Wasmer
export WASMER_DIR="/home/darkvoid/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"

export WASMTIME_HOME="$HOME/.wasmtime"
export PATH="$HOME/.local/bin/wabt-1.0.29/bin:$WASMTIME_HOME/bin:$PATH"
