---
- hosts: controllers
  become: yes
  gather_facts: true
  tasks:
    - import_tasks: ../tasks/user.yml
    - import_tasks: ../tasks/arch.yml
    - import_tasks: ../tasks/hello.yml
    - import_tasks: ../tasks/directories-k8s.yml
    - import_tasks: ../tasks/k0s-certs.yml
