---
- hosts: k8s
  become: yes
  gather_facts: true
  tasks:
    - import_tasks: ../tasks/user.yml
    - import_tasks: ../tasks/arch.yml
    - import_tasks: ../tasks/hello.yml
    - import_tasks: ../tasks/directories-k8s.yml
    - import_tasks: ../tasks/k0s-install.yml
    - import_tasks: ../tasks/k0s-setup.yml
    - import_tasks: ../tasks/k0s-certs.yml
    - import_tasks: ../tasks/k0s-service-install.yml
