#!/bin/env bash

# Add more using 'source $HOME/Devlabs/cmd/@PATH'

source $HOME/.cargo/env

source $DOTFILES/alias
source $DOTFILES/paths
source $DOTFILES/nvm
source $DOTFILES/emsdk
source $DOTFILES/golang
source $DOTFILES/git
source $DOTFILES/android
source $DOTFILES/functions
# source $DOTFILES/java_envs
