#!/bin/sh

# Install Mackup with PIP
pip install --upgrade mackup

# install ohmybash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" > /dev/null

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 

# install pyenv
git clone https://github.com/pyenv/pyenv.git ~/.pyenv

# install go
brew install go

# install github sync
git clone https://github.com/oxzi/github-orga-sync ~/.github-org-sync && cd ~/.github-org-sync && go install && cd -

# install rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
cd ~/.rbenv && src/configure && make -C src && cd -
~/.rbenv/bin/rbenv init

# install sdkman
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

# install rustlang
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# setup nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

# setup yay
git clone https://aur.archlinux.org/yay.git ~/bin/yay

