- name: Create an internal macvlan network
  when: enable_swag_internal | default(False)
  docker_network:
    name: swag_internal_macvlan
    driver: macvlan
    driver_options:
      parent: "{{ swag_interface }}"
    ipam_config:
      - subnet: "{{ swag_network }}"
        gateway: "{{ swag_gateway }}"

- name: Create a public macvlan network
  when: enable_swag_public | default(False)
  docker_network:
    name: swag_public_macvlan
    driver: macvlan
    driver_options:
      parent: enp5s0
    ipam_config:
      - subnet: "{{ dmz_network }}"
        gateway: "{{ dmz_gateway }}"
