---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: authelia
#---
#apiversion: v1
#kind: PersistentVolume
#metadata:
#  name: authelia-conf
#spec:
#  storageClassName: openebs-default
#  namespace: authelia
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: authconf
#  namespace: authelia
#spec:
#  storageClassName: """
#  volumeName:
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: authelia
#  name: authelia
#  labels:
#    app: authelia
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: authelia
#  template:
#    metadata:
#      labels:
#        app: authelia
#    spec:
#      volumes:
#        - name: authelia-conf
#          persistentVolumeClaim:
#            claimName: authconf
#      containers:
#        - name: authelia
#          image: authelia/authelia
#          ports:
#            - containerPort: 8080
#          volumeMounts:
#            - name: authconf
#              mountPath: /etc/authelia
#---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: authelia
#  name: authelia
#  labels:
#    app: authelia
#spec:
#  selector:
#    app: authelia
#  ports:
#    - port: 8080
#      name: authelia
#  externalTrafficPolicy: local
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: authelia-ingress
#  namespace: authelia
#spec:
#  tls:
#    - hosts:
#        - auth.ewe-studios.com
#    secretName: ewe-studios-com-staging-cert-tls
#  rules:
#    - http:
#        paths:
#          - path: /
#            pathType: Exact
#            backend:
#              service:
#                name: authelia
#                port:
#                  number: 8080
