#!/bin/bash

# load our defined colors
source "$CONFIG_DIR/colors.sh" 

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

bar_default=(
  height=37   
  blur_radius=30
  position=top
  sticky=off 
  padding_left=10 
  padding_right=10
  color=$BAR_COLOR
)

sketchybar --bar "${bar_default[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro:Semibold:14.0"  #icon.font="Hack Nerd Font:Bold:17.0"
  label.font="SF Pro:Semibold:14.0" #label.font="Hack Nerd Font:Bold:14.0"
  label.color=$WHITE
  padding_left=5
  padding_right=5
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=10
  background.color=$ITEM_BG_COLOR       
  background.corner_radius=5            
  background.height=24
)
sketchybar --default "${default[@]}"


##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.
#

# -- Left Side Items --
source "$ITEM_DIR/spaces.sh" 
source "$ITEM_DIR/front_app.sh" 

# -- Middle Items --
source "$ITEM_DIR/media.sh" 


# -- Right Side Items --
source "$ITEM_DIR/calendar.sh" 
source "$ITEM_DIR/volume.sh" 
source "$ITEM_DIR/battery.sh" 
source "$ITEM_DIR/cpu.sh" 



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
