#!/bin/sh

alias pbcopy='xclip -selection clipboard'
alias ssh_up='eval $(ssh-agent)'
alias pbpaste='xclip -selection clipboard -o'
alias edit_aliases="vim ~/.bash_aliases"
alias edit_profile="vim ~/.profile"
alias edit_bash="vim ~/.bashrc"
alias mycode="$HOME/Devlabs/code"

# git
alias gclone="git clone "
alias gcl="git clone "

# wget
alias pullsite="wget -r -erobots=off -p -k "

# docker
alias dok="docker"

# k8s, microk8s
alias mks="microk8s"
alias mk="microk8s kubectl"
alias k="kubectl"

# dotfiles
alias dotfiles_commit="cd $HOME/dotfiles && git commit -am 'UPT: Updated dotfiles'; cd -"
alias dotfiles_push="cd $HOME/dotfiles && git push origin master; cd -"

# playlist

alias pyoutube-audio='youtube-dl -ic -o "./audios/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist --extract-audio --audio-format mp3 --audio-quality 0'
alias pyoutube='youtube-dl -f best --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist'
alias pyoutube720='youtube-dl -f "bestvideo[height=720]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist'
alias pyoutube360='youtube-dl -f "bestvideo[height=360]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist'

# individual

alias prive-ssh='GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ecdsa_prive"'
alias influx6-ssh='GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ecdsa"'

alias youtube-audio='youtube-dl -ic -o "./audios/%(title)s.%(ext)s" --extract-audio --audio-format mp3 --audio-quality 0'
alias youtube='youtube-dl -f best --ignore-errors -o "./%(title)s.%(ext)s"'
alias youtube720='youtube-dl -f "bestvideo[height=720]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(title)s.%(ext)s"'
alias youtube360='youtube-dl -f "bestvideo[height=360]+bestaudio/bestvideo+bestaudio" --ignore-errors -o "./%(title)s.%(ext)s"'

alias start-sentinel=" sudo /opt/sentinelone/bin/sentinelctl control start"
alias stop-sentinel=" sudo /opt/sentinelone/bin/sentinelctl control stop"

# java
alias java8="/usr/lib/jvm/java-8-openjdk/bin/java"

