#!/bin/sh

alias pbcopy='xclip -selection clipboard'
alias ssh_up='eval $(ssh-agent)'
alias pbpaste='xclip -selection clipboard -o'
alias edit_aliases="vim ~/.bash_aliases"
alias edit_profile="vim ~/.profile"
alias edit_bash="vim ~/.bashrc"

# docker
alias dok="docker"

# k8s, microk8s
alias k="kubectl"

# dotfiles
alias dotfiles_commit="cd $HOME/dotfiles && git commit -am 'UPT: Updated dotfiles'; cd -"
alias dotfiles_push="cd $HOME/dotfiles && git push origin master; cd -"

# Download as audio in respective folder
alias youtube-audio='youtube-dl -ic -o "./audios/%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist --extract-audio --audio-format mp3 --audio-quality 0'

# Download as video in respective folder
alias youtube='youtube-dl -f best --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist'

# Download as video in respective folder
alias youtube720='youtube-dl -f "bestvideo[height=720]+bestaudio" --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist'

alias youtube360='youtube-dl -f "bestvideo[height=360]+bestaudio" --ignore-errors -o "./%(playlist)s/%(playlist_index)s- %(title)s.%(ext)s" --yes-playlist'
