#!/bin/env bash

# Add more using 'source $HOME/Devlabs/cmd/@PATH'

source $HOME/.cargo/env

source $Dotfiles/Mackup/alias
source $Dotfiles/Mackup/paths
source $Dotfiles/Mackup/nvm
source $Dotfiles/Mackup/emsdk
source $Dotfiles/Mackup/golang
source $Dotfiles/Mackup/git
source $Dotfiles/Mackup/android
source $Dotfiles/Mackup/functions
# source $Dotfiles/java_envs
