#!/bin/env bash

# Add more using 'source $HOME/Devlabs/cmd/@PATH'


source $Dotfiles/Mackup/paths
source $Dotfiles/Mackup/alias
source $Dotfiles/Mackup/editor
source $Dotfiles/Mackup/deno
source $Dotfiles/Mackup/emsdk
source $Dotfiles/Mackup/golang
source $Dotfiles/Mackup/git
source $Dotfiles/Mackup/net
source $Dotfiles/Mackup/android
source $Dotfiles/Mackup/functions
source $Dotfiles/Mackup/docker
source $Dotfiles/Mackup/microk8s
source $Dotfiles/Mackup/python
source $Dotfiles/Mackup/flutter
source $Dotfiles/Mackup/sdkman

