#!/bin/env bash

killNodeJS(){
 killall -9 node
}

reload() {
 source "$DOTFILES/Mackup/config"
}

fl(){
 if [[ -x "$(command -v bundler)" ]]; then
   bundler exec fastlane $*
 elif [[ -x "$(command -v fastlane)" ]]; then
    fastlane $*
 else
   echo "fastlane is not install, do 'sudo gem install bundler fastlane'"
 fi
}
