#!/bin/env bash

nodekill(){
 killall -9 node
}

priveDesktopTransferOut(){
	scp $3 $1 darkvoid@10.11.0.35:/home/darkvoid/$2
}

priveDesktopTransferIn(){
	scp $3 darkvoid@10.11.0.35:/home/darkvoid/$1 $2
}

reload() {
 source "~/.profile"
}

unset_aws() {
 set +x
 unset AWS_PROFILE
 unset AWS_DEFAULT_PROFILE
 unset AWS_SECRET_ACCESS_KEY
 unset AWS_ACCESS_KEY_ID
 set +x
}

run() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
}

