#!/bin/sh

token=$(microk8s kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)

export K8S_DASHBOARD_TOKEN=$token

dashboardToken(){
	microk8s kubectl -n kube-system describe secret $token
}
