#!/bin/sh

token=$(microk8s kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)

alias m="microk8s"
alias k8="microk8s.kubectl"
alias knodes="microk8s.kubectl get nodes"

export K8S_DASHBOARD_TOKEN=$token

dashboardToken(){
	microk8s kubectl -n kube-system describe secret $token
}
