#!/bin/env bash

export Devlabs=$HOME/Devlabs
export Local=$HOME/local
export SRC=$Devlabs/src
export DOOMDIR=$HOME/.doom.d/
export EMACSDIR=$HOME/.emacs.d/
export GITHUB=$SRC/github.com
export ZIG=$GITHUB/ziglang/zig/
export NPM=$HOME/.node_modules
export EMSC=$SRC/github.com/juj/emsdk
export LINUXBREW=/home/linuxbrew/.linuxbrew

export mycode=$Devlabs/code
export github=$SRC/github.com
export influx6=$SRC/github.com/influx6
export forkkit=$SRC/github.com/forkkit
export work=$SRC/github.com/JSchillinger

export NODE_OPTIONS="--max-old-space-size=4096"

export EMCC=$GITHUB/juj/emsdk
export BOOST_ROOT=/usr/boost
export ANACONDA_PATH=$HOME/anaconda3
export SDKManager=$Devlabs/tools

export RBENV=$HOME/.rbenv/

export PATH=/usr/local/sbin:$PATH
export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$Devlabs/bin:$Local/bin:$PATH

export LDFLAGS="-L/usr/local/opt/ncurses/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include"

# add nix based information
export PATH="$HOME/.rbenv/bin:$PATH"

export ANDROID_HOME=$HOME/Devlabs/android
export NODE_MODULES=$HOME/node_modules
export ANDROID_SDK_BIN=$ANDROID_HOME/sdk/cmdline-tools/latest/bin
export ANDROID_TOOLS_BIN=$ANDROID_HOME/sdk/tools/bin

export PATH=$NODE_MODULES/bin:$NODE_MODULES/.bin:$LINUXBREW/bin:$Projects/bin:$HOME/local/bin:$HOME/local/go/bin:$HOME/.cargo/bin:$PATH
export PATH=$ANDROID_TOOLS_BIN:$HOME/Devlabs/bin:$ANDROID_SDK_BIN:$HOME/Devlabs/flutter/bin:$HOME/Devlabs/local/bin:$HOME/Devlabs/local/sbin/bin:$HOME/Devlabs/local/sbin/go/bin:$PATH

export PATH="$PATH:$HOME/.rvm/bin"
export Dotfiles=$HOME/dotfiles

export EDITOR='vim'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'


export SDKMAN_DIR="$HOME/.sdkman"
export NVM_DIR="$HOME/.nvm"
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/dotfiles/bin:$PATH"
export PATH=$HOME/apache-tomcat-7.0.104/bin:$PATH
export PATH=/snap/bin:$HOME/.local/bin:$HOME/Devlabs/bin:$PATH
export PATH=$HOME/apache-tomcat-7.0.104/bin:$HOME/apache-tomcat-7.0.105/bin:$PATH

[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then . $HOME/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
if [ -e $HOME/.profile.custom ]; then . $HOME/.profile.custom; fi # load .profile.custom
if [ -e $HOME/.profile.prive ]; then . $HOME/.profile.prive; fi # load .profile.custom
if [ -e $HOME/.profile.prive.ci ]; then . $HOME/.profile.prive.ci; fi # load .profile.custom
if [ -e $HOME/.profile.prive.aws ]; then . $HOME/.profile.prive.aws; fi # load .profile.custom
if [ -e $HOME/.profile.firebase ]; then . $HOME/.profile.firebase; fi # load .profile.custom
if [ -e $HOME/.profile.git ]; then . $HOME/.profile.git; fi # load .profile.custom
if [ -e $HOME/.profile.linode ]; then . $HOME/.profile.linode; fi # load .profile.custom

test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)


# add linuxbrew to the PATH
export PATH=$PATH:$HOME/Devlabs/pkg/go/bin:$HOME/go/bin:$HOME/Devlabs/appImages

# add Pulumi to the PATH
export PATH=$PATH:$HOME/.pulumi/bin

## restore quiet mode when set -x is on
##set +x


export PATH=$PATH:$HOME/Devlabs/pkg/Flutter/flutter/bin:opt/net.downloadhelper.coapp/bin/

set +o noclobber
. "$HOME/.cargo/env"
