#!/bin/env bash

export Devlabs=$HOME/Devlabs
export Local=$HOME/local
export SRC=$Devlabs/src
export DOOMDIR=$HOME/.doom.d/
export EMACSDIR=$HOME/.emacs.d/
export GITHUB=$SRC/github.com
export ZIG=$GITHUB/ziglang/zig/
export NPM=$HOME/.node_modules
export EMSC=$SRC/github.com/juj/emsdk
export LINUXBREW=/home/linuxbrew/.linuxbrew

export mycode=$Devlabs/code
export github=$SRC/github.com
export influx6=$SRC/github.com/influx6
export forkkit=$SRC/github.com/forkkit
export work=$SRC/github.com/JSchillinger

export NODE_OPTIONS="--max-old-space-size=4096"

export EMCC=$GITHUB/juj/emsdk
export BOOST_ROOT=/usr/boost
export ANACONDA_PATH=$HOME/anaconda3
export SDKManager=$Devlabs/tools

export RBENV=$HOME/.rbenv/

export PATH=/usr/local/sbin:$PATH
export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$Devlabs/bin:$Local/bin:$PATH

export LDFLAGS="-L/usr/local/opt/ncurses/lib"
export CPPFLAGS="-I/usr/local/opt/ncurses/include"

# add nix based information
export PATH="$HOME/.rbenv/bin:$PATH"

export ANDROID_HOME=$HOME/Devlabs/android
export ANDROID_SDK_BIN=$ANDROID_HOME/sdk/cmdline-tools/latest/bin
export ANDROID_TOOLS_BIN=$ANDROID_HOME/sdk/tools/bin

export PATH=$LINUXBREW/bin:$Projects/bin:$HOME/local/bin:$HOME/local/go/bin:$HOME/.cargo/bin:$PATH
export PATH=$ANDROID_TOOLS_BIN:$HOME/Devlabs/bin:$ANDROID_SDK_BIN:$HOME/Devlabs/flutter/bin:$HOME/Devlabs/local/bin:$HOME/Devlabs/local/sbin/bin:$HOME/Devlabs/local/sbin/go/bin:$PATH
