---
- name: Enable IPv4 forwarding
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv4.ip_forward=1"
- name: Enable IPv6 forwarding
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv6.conf.all.ip_forward=1"
