---
- name: Make sure ddclient is installed
  package:
    name: ddclient
    state: present


- name: Install the configuration file
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart ddclient service

- name: Make sure the ddclient service is started & enabled
  service:
    name: ddclient
    state: started
    enabled: yes
