---
networks:
  # These are the different physical hosts in our network
  darkmini:
    host:
      ip: 192.168.128.50
      lidr: 192.168.128.50/32
      # this can be your public ip from your ISP (you can use value from machine_remote_ip)
      gateway: 192.168.128.50
      public_gateway: machine.ewe-studios.com
      cidr: 192.168.128.0/24
      wg:
        port: 58190
        ip: 10.0.10.10
        lidr: 10.0.10.10/32
        cidr: 10.0.10.0/24
    vms:
      - name: controller
        ip: 10.0.50.2
        lidr: 10.0.50.2/32
        cidr: 10.0.50.0/24
        port_mappings:
#          - bind_address: 192.168.128.50
#            vm_port: 58190
#            host_port: 28191
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.11
          lidr: 10.0.10.11/32
          cidr: 10.0.10.0/24
      - name: worker1
        ip: 10.0.50.3
        lidr: 10.0.50.3/32
        cidr: 10.0.50.0/24
        port_mappings:
#          - bind_address: 192.168.128.50
#            vm_port: 58190
#            host_port: 28192
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.13
          lidr: 10.0.10.13/32
          cidr: 10.0.10.0/24
      - name: worker2
        ip: 10.0.50.4
        lidr: 10.0.50.4/32
        cidr: 10.0.50.0/24
        port_mappings:
#          - bind_address: 192.168.128.50
#            vm_port: 58190
#            host_port: 28193
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.14
          lidr: 10.0.10.14/32
          cidr: 10.0.10.0/24
  slave1:
    host:
      ip: 192.168.128.10
      lidr: 192.168.128.10/32
      # this can be your public ip from your ISP (you can use value from machine_remote_ip)
      gateway: 192.168.128.10
      public_gateway: machine.ewe-studios.com
      cidr: 192.168.128.0/24
      wg:
        port: 58190
        ip: 10.0.10.20
        lidr: 10.0.10.20/32
        cidr: 10.0.10.0/24
    vms:
      - name: controller
        ip: 10.0.51.2
        lidr: 10.0.51.2/32
        cidr: 10.0.51.0/24
        port_mappings:
#          - bind_address: 192.168.128.10
#            vm_port: 58190
#            host_port: 28191
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.21
          lidr: 10.0.10.21/32
          cidr: 10.0.10.0/24
      - name: worker1
        ip: 10.0.51.3
        lidr: 10.0.51.3/32
        cidr: 10.0.51.0/24
        port_mappings:
#          - bind_address: 192.168.128.10
#            vm_port: 58190
#            host_port: 28192
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.22
          lidr: 10.0.10.22/32
          cidr: 10.0.10.0/24
      - name: worker2
        ip: 10.0.51.4
        lidr: 10.0.51.4/32
        cidr: 10.0.51.0/24
        port_mappings:
#          - bind_address: 192.168.128.10
#            vm_port: 58190
#            host_port: 28193
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.23
          lidr: 10.0.10.23/32
          cidr: 10.0.10.0/24
  slave2:
    host:
      ip: 192.168.128.20
      lidr: 192.168.128.20/32
      # this can be your public ip from your ISP (you can use value from machine_remote_ip)
      public_gateway: machine.ewe-studios.com
      gateway: 192.168.128.20
      cidr: 192.168.128.0/24
      wg:
        port: 58190
        ip: 10.0.10.30
        lidr: 10.0.10.30/32
        cidr: 10.0.10.0/24
    vms:
      - name: controller
#        ip: 10.0.52.2
#        lidr: 10.0.52.2/32
#        cidr: 10.0.52.0/24
        port_mappings:
#          - bind_address: 192.168.128.20
#            vm_port: 58190
#            host_port: 28191
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.20
          lidr: 10.0.10.20/32
          cidr: 10.0.10.0/24
      - name: worker1
        ip: 10.0.52.3
        lidr: 10.0.52.3/32
        cidr: 10.0.52.0/24
        port_mappings:
#          - bind_address: 192.168.128.20
#            vm_port: 58190
#            host_port: 28192
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.30
          lidr: 10.0.10.30/32
          cidr: 10.0.10.0/24
      - name: worker2
        ip: 10.0.52.4
        lidr: 10.0.52.4/32
        cidr: 10.0.52.0/24
        port_mappings:
#          - bind_address: 192.168.128.20
#            vm_port: 58190
#            host_port: 28193
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.40
          lidr: 10.0.10.40/32
          cidr: 10.0.10.0/24
  darkcoder:
    host:
      ip: 192.168.138.159
      lidr: 192.168.138.159/32
      gateway: 192.168.138.159 # can be public ip from your ISP (you can use value from machine_remote_ip)
      public_gateway: 192.168.138.159
      cidr: 192.168.138.0/24
      wg:
        port: 58190
        ip: 10.0.10.10
        lidr: 10.0.10.10/32
        cidr: 10.0.10.0/24
    vms:
      - name: controller
        ip: 10.0.53.2
        lidr: 10.0.53.2/32
        cidr: 10.0.53.0/24
        port_mappings:
#          - bind_address: 192.168.128.159
#            vm_port: 58190
#            host_port: 28191
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.20
          lidr: 10.0.10.20/32
          cidr: 10.0.10.0/24
      - name: worker1
        ip: 10.0.53.3
        lidr: 10.0.53.3/32
        cidr: 10.0.53.0/24
        port_mappings:
#          - bind_address: 192.168.128.159
#            vm_port: 58190
#            host_port: 28192
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.30
          lidr: 10.0.10.30/32
          cidr: 10.0.10.0/24
      - name: worker2
        ip: 10.0.53.4
        lidr: 10.0.53.4/32
        cidr: 10.0.53.0/24
        port_mappings:
#          - bind_address: 192.168.128.159
#            vm_port: 58190
#            host_port: 28193
#            protocol: udp
        wg:
          port: 58190
          ip: 10.0.10.40
          lidr: 10.0.10.40/32
          cidr: 10.0.10.0/24
