---

mesh_name: "slave1"
network_name: "slave10"
mesh: [ "slave1" ]
peers: [ "darkmini", "slave2" ]

network_mesh:
  vms: "{{ dict(mesh | zip(mesh | map('extract', networks) | map(attribute='vms'))) }}"
  host: "{{ dict(mesh | zip(mesh | map('extract', networks) | map(attribute='host') | flatten )) }}"

peers_mesh:
  peers_vms: "{{ dict(peers | zip(peers | map('extract', networks) | map(attribute='vms'))) }}"
  peers_hosts: "{{ dict(peers | zip(peers | map('extract', networks) | map(attribute='host') | flatten )) }}"

host: "{{ network_mesh.host[mesh_name] }}"
controller_name: "{{ network_mesh.vms[mesh_name][0].name }}"
worker1: "{{ network_mesh.vms[mesh_name][1].name }}"
worker2: "{{ network_mesh.vms[mesh_name][2].name }}"

infra:
  name: "{{ mesh_name }}"
  mesh: "{{ network_mesh }}"
  peers: "{{ peers_mesh }}"
  host: "{{ host }}"
  device:
    iface: "eno1"
  caddy2:
    serverIP: "{{ networks[mesh_name].host.ip }}"
  wg:
    name: "{{ network_name }}"
    port: "{{ networks[mesh_name].host.wg.port }}"
    lidr: "{{ networks[mesh_name].host.wg.lidr }}"
    cidr: "{{ networks[mesh_name].host.wg.cidr }}"
    private_key: "{{ secrets[mesh_name].host.private_key }}"
    public_key: "{{ secrets[mesh_name].host.public_key }}"
  vms:
    - vm_name: "{{ controller_name }}"
      vm_cpu: 2
      vm_memory: 2G
      vm_disk: 3GB
      vm_image: "localhost:5443/machine_image:{{ vps_image_version }}"
      owner_tag: "machine"
      owner_name: "{{ ansible_hostname }}"
      network: "{{ network_mesh.vms[mesh_name][0] }}"
      secrets:
        private_key: "{{ secrets[mesh_name][controller_name].private_key }}"
        public_key: "{{ secrets[mesh_name][controller_name].public_key }}"
      labels:
        - name: "group"
          value: "controller"
        - name: "desc"
          value: "controller vm for infrastructure in {{ network_name }}"
      annotations:
        - name: "group"
          value: "controller"
    - vm_name: "{{ worker1 }}"
      vm_cpu: 2
      vm_memory: 2G
      vm_disk: 3GB
      vm_image: "localhost:5443/machine_image:{{ vps_image_version }}"
      owner_tag: "machine"
      owner_name: "{{ ansible_hostname }}"
      network: "{{ network_mesh.vms[mesh_name][1] }}"
      secrets:
        private_key: "{{ secrets[mesh_name][worker1].private_key }}"
        public_key: "{{ secrets[mesh_name][worker1].public_key }}"
      labels:
        - name: "group"
          value: "workers"
        - name: "desc"
          value: "worker vm for infrastructure in {{ network_name }}"
      annotations:
        - name: "group"
          value: "workers"
    - vm_name: "{{ worker2 }}"
      vm_cpu: 2
      vm_memory: 2G
      vm_disk: 3GB
      vm_image: "localhost:5443/machine_image:{{ vps_image_version }}"
      owner_tag: "machine"
      owner_name: "{{ ansible_hostname }}"
      network: "{{ network_mesh.vms[mesh_name][2] }}"
      secrets:
        private_key: "{{ secrets[mesh_name][worker2].private_key }}"
        public_key: "{{ secrets[mesh_name][worker2].public_key }}"
      labels:
        - name: "group"
          value: "workers"
        - name: "desc"
          value: "worker vm for infrastructure in {{ network_name }}"
      annotations:
        - name: "group"
          value: "workers"

