---
- hosts: masters
  become: yes
  gather_facts: true
  tasks:
    - import_tasks: ../tasks/arch.yml
    - import_tasks: ../tasks/user.yml
    - import_tasks: ../tasks/directories-infra.yml
    - import_tasks: ../tasks/directories-tower-sym.yml
    - import_tasks: ../tasks/docker-networks-apps.yml
    - import_tasks: ../tasks/docker-file-browser.yml
