---
- hosts: portainer_clients
  become: yes
  gather_facts: true
  tasks:
    - import_tasks: ../tasks/arch.yml
    - import_tasks: ../tasks/user.yml
    - import_tasks: ../tasks/directories-infra.yml
    - import_tasks: ../tasks/docker-networks-infra.yml
    - import_tasks: ../tasks/docker-portainer.yml
