---
- name: Make sure the Flame container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "pawelmalak/flame:latest"
    pull: yes
    networks:
      - name: swag_internal_macvlan
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "PASSWORD": "flame"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/app/data"
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: unless-stopped
