---
- name: Stop caddy if already installed (its allowed to fail)
  ansible.builtin.shell: "docker kill caddy_server"
  ignore_errors: yes
- name: Remove old caddy server (its allowed to fail)
  ansible.builtin.shell: "docker rm caddy_server"
  ignore_errors: yes
- name: Start caddy
  ansible.builtin.shell:
    cmd: >
      docker run -d 
      -p 80:80 -p 433:433 -p 433:433/udp 
      -v {{ewe_dir}}/caddy2/machine/Caddy.json:/etc/caddy/Caddyfile.json
      -v {{ewe_dir}}/caddy2/machine/data:/data 
      -v {{ewe_dir}}/caddy2/machine/config:/config
      -v {{ewe_dir}}/caddy2/machine/sites:/srv
      --name caddy_server
      --restart always
      localhost:5443/machine_caddy:{{ vps_image_version }}
      caddy run --config /etc/caddy/Caddyfile.json --adapter json5