---
- name: Create a MySQL database for Drupal.
  mysql_db: "db={{ domain }} state=present"

- name: Create a MySQL user for Drupal.
  mysql_user:
    name: "{{ domain }}"
    password: "1234"
    priv: "{{ domain }}.*:ALL"
    host: localhost
    state: present

# TODO: See https://github.com/geerlingguy/ansible-for-devops/issues/297
- name: Create a MySQL user for Drupal.
  mysql_user:
    name: "{{ domain }}"
    password: "1234"
    priv: "{{ domain }}.*:ALL"
    host: localhost
    state: present
