- name: Create an internal macvlan network
  when: enable_homeassistant | default(False)
  docker_network:
    name: iot_macvlan
    driver: macvlan
    driver_options:
      parent: "{{ iot_interface }}"
    ipam_config:
      - subnet: "{{ iot_network }}"
        gateway: "{{ iot_gateway }}"
