- name: Get tower.remote ip
  command: "curl ifconfig.me"
  register: machine_internet_ip
- set_fact:
    machine_remote_ip: "{{ machine_internet_ip.stdout }}"
    machine_hostname: "{{ ansible_hostname }}"
    machine_local_ip: "{{ ansible_default_ipv4.address }}"
