---
- name: Make sure the Unifi container is created and running
  docker_container:
    name: '{{ container_name }}'
    image: "ghcr.io/linuxserver/unifi-controller"
    pull: true
    networks:
      - name: swag_internal_macvlan
        ipv4_address: "{{ ip_address }}"
    state: 'started'
    env:
      PUID: "{{ guid }}"
      PGID: "{{ guid }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped
