- name: Create code server directories
  file:
    path: "{{home}}/{{item}}"
    owner: "{{user.stdout}}"
    mode: "0755"
    state: directory
  loop:
    - "idea"
    - "Lab/config"
    - "Lab/codes"
- name: Create 'services' directories servers
  file:
    path: "/home/{{user.stdout}}/{{item}}"
    owner: "{{user.stdout}}"
    mode: "0755"
    state: directory
  loop:
    - "services"
