- name: Check 'directories' exist else create it
  file:
    path: "/home/{{user.stdout}}/{{item}}"
    owner: "{{user.stdout}}"
    mode: "0755"
    state: directory
  loop:
    - "heimdall"

- name: check if heimdall volume exists
  shell: "docker volume ls | grep 'heimdall_volume'"
  ignore_errors: true
  register: volume_ready

- name: Create volume for heimdall
  shell: "docker volume create --driver local --opt type=none --opt device={{fs_root}}/Portainer --opt o=bind heimdall_volume"
  when: volume_ready.rc == 1

- name: Copy docker-compose-heimdall to server
  copy:
    src : "./files/docker-compose-heimdall.yml"
    dest: "/home/{{user.stdout}}/services/docker-compose-heimdall.yml"
    force: yes

- name: Start docker services
  command: "docker-compose --project-name=heimdall -f /home/{{user.stdout}}/services/docker-compose-heimdall.yml up -d --remove-orphans"
