- name: update apt packages
  ignore_errors: yes
  apt:
    update_cache: yes
- name: Install coding packages
  apt:
    pkg:
      - rustc
      - scala
      - ca-certificates
      - gcc
      - llvm
      - openjdk-8-jdk-headless
      - openjdk-11-jdk-headless
      - golang
      - python3
      - python3-pip
      - gettext
      - autoconf
      - automake
      - cmake
      - g++
    state: present
- name: Apt handle unattended-upgrades
  command: apt-get install -y unattended-upgrades
