---
- hosts: media-servers
  become: yes
  gather_facts: true
  tasks:
    - import_tasks: ../tasks/arch.yml
    - import_tasks: ../tasks/user.yml
    - import_tasks: ../tasks/directories-all.yml
    - import_tasks: ../tasks/directories-unraid.yml
    - import_tasks: ../tasks/docker-networks-infra.yml
    - import_tasks: ../tasks/docker-networks-apps.yml
    - import_tasks: ../tasks/docker-unraid.yml
