---
- name: Make sure the Plex container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/plex"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ dashboard_name }}"
      "flame.url": "{{ url }}"
      "flame.icon": "custom"
    networks:
      - name: swag_internal_macvlan
        ipv4_address: "{{ ip_address }}"
    devices:
      - "/dev/dri:/dev/dri"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/tv"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
    restart_policy: unless-stopped
