---
- name: Create template for generating vms
  no_log: yes
  become_user: "{{ user_account }}"
  template:
    src: "{{role_path}}/files/ignite_vm.j2"
    dest: "{{infra.directory}}/{{infra.name}}/vm_{{item.vm_name}}.yaml"
    owner: "{{ user_account }}"
    mode: "0600"
    force: yes
  with_items: "{{ infra.vms }}"