---
- name: Create 'directories' for host
  no_log: yes
  become_user: "{{user_account}}"
  file:
    path: "{{infra.directory}}/{{ infra.name }}"
    owner: "{{user_account}}"
    mode: "0755"
    state: directory
- name: Create 'directories' for vm mounts
  no_log: yes
  become_user: "{{user_account}}"
  file:
    path: "{{infra.directory}}/{{ item.vm_name }}"
    owner: "{{user_account}}"
    mode: "0755"
    state: directory
  with_items: "{{ infra.vms }}"
