---
- name: Check if VMs exists but are running, and recycle_vms is on, then kill them
  no_log: no
  ignore_errors: yes
  ansible.builtin.shell: "ignite --ignite-config {{ewe_dir}}/ignite-vps/registry.yaml kill {{item.vm_name}}"
  when: live_vms[item.vm_name].exist|bool == True and recycle_vms|bool == True
  loop: "{{ infra.vms }}"
  loop_control:
    index_var: index
- name: Check if recycle_vms is on, then remove them
  no_log: no
  ignore_errors: yes
  ansible.builtin.shell: "ignite --ignite-config {{ewe_dir}}/ignite-vps/registry.yaml rm -f {{item.vm_name}}"
  when: recycle_vms|bool == True
  loop: "{{ infra.vms }}"
  loop_control:
    index_var: index
- name: Check if VMs exists but are not running, if so delete them
  no_log: no
  ignore_errors: yes
  ansible.builtin.shell: "ignite --ignite-config {{ewe_dir}}/ignite-vps/registry.yaml rm -f {{item.vm_name}}"
  when: live_vms[item.vm_name].exist|bool == True and live_vms[item.vm_name].running|bool == False
  loop: "{{ infra.vms }}"
  loop_control:
    index_var: index
- name: Create VMS from declarative file
  no_log: no
  ansible.builtin.shell: "ignite --ignite-config {{ewe_dir}}/ignite-vps/registry.yaml run --config {{infra.directory}}/{{infra.name}}/vm_{{item.vm_name}}.yaml"
  when: live_vms[item.vm_name].exist|bool == False or live_vms[item.vm_name].running|bool == False
  loop: "{{ infra.vms }}"
  loop_control:
    index_var: index
