version: "3.5"

networks:
  portainer_network:
  default:
    external:
      name: infra-networks

volumes:
  portainer_volume:
    external: true


services:
  portainer_ce:
    image: "portainer/portainer-ce:2.11.1"
    privileged: true
    restart: unless-stopped
    ports:
      - "9080:8000"
      - "9043:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_volume:/data"

  portainer_agent:
    image: "portainer/agent:2.11.1"
    restart: unless-stopped
    privileged: yes
    ports:
      - "9001:9001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes:rw"
