---

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "authelia/authelia:latest"
    pull: true
    state: 'started'
    env:
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
    restart_policy: unless-stopped

- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_public_macvlan
    connected:
      - "{{ container_name }}"
    appends: yes
  when: enable_swag


- name: Create the configuration directory
  file:
    path: "{{ docker_dir }}/{{ container_name }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Install the configuration template
  template:
    src: configuration.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/configuration.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  notify:
    - Restart the docker container

- name: Install the users template
  template:
    src: users_database.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/users_database.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
  register: users
