---
# tasks file for ufw
- name: install ufw
  package:
    state: present
    pkg:
      - ufw
- name: Setup basic ufw rules
  ansible.builtin.command: "{{item}}"
  loop:
    - "ufw default deny incoming"
    - "ufw default allow outgoing"
    - "ufw allow from 192.168.128.0/24 to any port 5606"
    - "ufw allow from 10.0.10.0/24 to any port 5606"
    - "ufw allow from 10.0.11.0/24 to any port 5606"
    - "ufw allow from 10.0.12.0/24 to any port 5606"
    - "ufw allow from 10.0.13.0/24 to any port 5606"
    - "ufw allow ssh"
    - "ufw allow https"
    - "ufw allow http"
